In [56]:
import pandas as pd
import numpy as np

In [57]:
df_clean = pd.read_csv("../Clean_Input_Data/credit_card_churn_clean.csv")
df_clean

,Unnamed: 0,customer_id,customer_age,gender,dependent_count,education_level,marital_status,income_category,card_category,months_on_book,total_relationship_count,credit_limit,total_revolving_bal,active_customer
0,0,768805383,45,M,3,1,married,2,blue,39,5,12691.0,777,True
1,1,818770008,49,F,5,2,single,0,blue,44,6,8256.0,864,True
2,2,713982108,51,M,3,2,married,3,blue,36,4,3418.0,0,True
3,4,709106358,40,M,3,0,married,2,blue,21,5,4716.0,0,True
4,5,713061558,44,M,2,2,married,1,blue,36,3,4010.0,1247,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7076,10120,710841183,54,M,1,1,single,2,blue,34,5,13940.0,2109,True
7077,10121,713899383,56,F,1,2,single,0,blue,50,4,3688.0,606,True
7078,10122,772366833,50,M,2,2,single,1,blue,40,3,4003.0,1851,True
7079,10124,716506083,44,F,1,1,married,0,blue,36,5,5409.0,0,False
7080,10126,714337233,43,F,2,2,married,0,silver,25,6,10388.0,1961,False

In [58]:
df_clean.columns

Index(['Unnamed: 0', 'customer_id', 'customer_age', 'gender',
       'dependent_count', 'education_level', 'marital_status',
       'income_category', 'card_category', 'months_on_book',
       'total_relationship_count', 'credit_limit', 'total_revolving_bal',
       'active_customer'],
      dtype='object')

In [59]:
df_clean.describe()

,Unnamed: 0,customer_id,customer_age,dependent_count,education_level,income_category,months_on_book,total_relationship_count,credit_limit,total_revolving_bal
count,7081.000000,7.081000e+03,7081.000000,7081.000000,7081.000000,7081.000000,7081.000000,7081.000000,7081.000000,7081.000000
mean,4970.298122,7.390919e+08,46.347691,2.337805,1.819093,1.343313,35.981359,3.819376,8492.773831,1167.501624
std,2967.582990,3.685244e+07,8.041225,1.291649,1.303367,1.355904,8.002609,1.544444,9126.072520,812.315606
min,0.000000,7.080821e+08,26.000000,0.000000,0.000000,0.000000,13.000000,1.000000,1438.300000,0.000000
25%,2359.000000,7.130105e+08,41.000000,1.000000,1.000000,0.000000,31.000000,3.000000,2498.000000,463.000000
50%,4901.000000,7.178438e+08,46.000000,2.000000,2.000000,1.000000,36.000000,4.000000,4287.000000,1282.000000
75%,7551.000000,7.732370e+08,52.000000,3.000000,2.000000,3.000000,40.000000,5.000000,10729.000000,1781.000000
max,10126.000000,8.282989e+08,73.000000,5.000000,5.000000,4.000000,56.000000,6.000000,34516.000000,2517.000000

In [60]:
df_clean.dtypes

Unnamed: 0                    int64
customer_id                   int64
customer_age                  int64
gender                       object
dependent_count               int64
education_level               int64
marital_status               object
income_category               int64
card_category                object
months_on_book                int64
total_relationship_count      int64
credit_limit                float64
total_revolving_bal           int64
active_customer                bool
dtype: object

In [61]:
print(df_clean.gender.unique())
print(df_clean.marital_status.unique())
print(df_clean.card_category.unique())
print(df_clean.active_customer.unique())
print(df_clean.active_customer.unique().sum())

df_clean['gender'] = df_clean.gender.replace({
    'M':0,
    'F':1
})

df_clean['marital_status'] = df_clean.marital_status.replace({
    'married':0, 
    'single':1, 
    'divorced':2
})

df_clean['card_category'] = df_clean.card_category.replace({
    'blue':0, 
    'gold':1, 
    'silver':2, 
    'platinum':3
})

df_clean['active_customer'] = df_clean.active_customer.replace({
    True:0,
    False:1
})

['M' 'F']
['married' 'single' 'divorced']
['blue' 'gold' 'silver' 'platinum']
[ True False]
1

In [62]:
df_clean

,Unnamed: 0,customer_id,customer_age,gender,dependent_count,education_level,marital_status,income_category,card_category,months_on_book,total_relationship_count,credit_limit,total_revolving_bal,active_customer
0,0,768805383,45,0,3,1,0,2,0,39,5,12691.0,777,0
1,1,818770008,49,1,5,2,1,0,0,44,6,8256.0,864,0
2,2,713982108,51,0,3,2,0,3,0,36,4,3418.0,0,0
3,4,709106358,40,0,3,0,0,2,0,21,5,4716.0,0,0
4,5,713061558,44,0,2,2,0,1,0,36,3,4010.0,1247,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7076,10120,710841183,54,0,1,1,1,2,0,34,5,13940.0,2109,0
7077,10121,713899383,56,1,1,2,1,0,0,50,4,3688.0,606,0
7078,10122,772366833,50,0,2,2,1,1,0,40,3,4003.0,1851,0
7079,10124,716506083,44,1,1,1,0,0,0,36,5,5409.0,0,1
7080,10126,714337233,43,1,2,2,0,0,2,25,6,10388.0,1961,1

In [68]:
X= df_clean.drop(columns=["Unnamed: 0","active_customer","customer_id"])
y=df_clean['active_customer']

X.head()

,customer_age,gender,dependent_count,education_level,marital_status,income_category,card_category,months_on_book,total_relationship_count,credit_limit,total_revolving_bal
0,45,0,3,1,0,2,0,39,5,12691.0,777
1,49,1,5,2,1,0,0,44,6,8256.0,864
2,51,0,3,2,0,3,0,36,4,3418.0,0
3,40,0,3,0,0,2,0,21,5,4716.0,0
4,44,0,2,2,0,1,0,36,3,4010.0,1247

In [70]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: active_customer, dtype: int64

In [71]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [72]:
X= scaler.fit_transform(X)

X

array([[-0.16760956, -0.95429837,  0.51270999, ...,  0.764487  ,
         0.460058  , -0.48076043],
       [ 0.32986222,  1.0478903 ,  2.06122755, ...,  1.41201481,
        -0.0259466 , -0.37365164],
       [ 0.57859811, -0.95429837,  0.51270999, ...,  0.1169592 ,
        -0.55611351, -1.43735275],
       ...,
       [ 0.45423017, -0.95429837, -0.26154879, ..., -0.53056861,
        -0.49200693,  0.84147915],
       [-0.29197751,  1.0478903 , -1.03580757, ...,  0.764487  ,
        -0.33793196, -1.43735275],
       [-0.41634545,  1.0478903 , -0.26154879, ...,  1.41201481,
         0.20768628,  0.97690406]])

In [73]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=20)

In [74]:
print(f"Shape of X_train is : {X_train.shape}")
print(f"Shape of X_test is : {X_test.shape}")
print(f"Shape of y_train is : {y_train.shape}")
print(f"Shape of y_test is : {y_test.shape}")

Shape of X_train is : (5664, 11)
Shape of X_test is : (1417, 11)
Shape of y_train is : (5664,)
Shape of y_test is : (1417,)

In [79]:
import xgboost
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

from sklearn.metrics import classification_report, accuracy_score, confusion_matrix, precision_score, recall_score, f1_score

In [80]:
algos = [LogisticRegression(), 
         DecisionTreeClassifier(), 
         RandomForestClassifier(), 
         XGBClassifier()]
names = ["Logistic Regression",
         "DecisionTree Classifier",
         "RandomForest Classifier", 
         "XGBoost Classifier"]
acc = []

In [81]:
for name in algos:
    model = name
    model.fit(X_train,y_train)
    y_pred = model.predict(X_test)
    accu = accuracy_score(y_test,y_pred)
    acc.append(accu)

In [82]:
acc

[0.8334509527170078,
 0.7854622441778405,
 0.8390966831333804,
 0.8348623853211009]

In [83]:
evaluation = pd.DataFrame({'Name':names, 'Accuracy_Score':acc})
evaluation

                      Name  Accuracy_Score
0      Logistic Regression        0.833451
1  DecisionTree Classifier        0.785462
2  RandomForest Classifier        0.839097
3       XGBoost Classifier        0.834862

## Hyparameter Tuning using GridSearchCV

In [87]:
from sklearn.model_selection import GridSearchCV
xgb_model= XGBClassifier()

In [88]:
params = {
    'n_estimators': [100,200,300],
    'max_depth': [1,2,3,4],
    'eta': [0.1,0.01,0.001]
}

In [89]:
cross_val = GridSearchCV(estimator=xgb_model,param_grid=params,verbose=2)
cross_val.fit(X_train,y_train)

Fitting 5 folds for each of 36 candidates, totalling 180 fits
[CV] END .............eta=0.1, max_depth=1, n_estimators=100; total time=   0.1s
[CV] END .............eta=0.1, max_depth=1, n_estimators=100; total time=   0.2s
[CV] END .............eta=0.1, max_depth=1, n_estimators=100; total time=   0.1s
[CV] END .............eta=0.1, max_depth=1, n_estimators=100; total time=   0.2s
[CV] END .............eta=0.1, max_depth=1, n_estimators=100; total time=   0.1s
[CV] END .............eta=0.1, max_depth=1, n_estimators=200; total time=   0.3s
[CV] END .............eta=0.1, max_depth=1, n_estimators=200; total time=   0.5s
[CV] END .............eta=0.1, max_depth=1, n_estimators=200; total time=   0.3s
[CV] END .............eta=0.1, max_depth=1, n_estimators=200; total time=   0.3s
[CV] END .............eta=0.1, max_depth=1, n_estimators=200; total time=   0.3s
[CV] END .............eta=0.1, max_depth=1, n_estimators=300; total time=   0.4s
[CV] END .............eta=0.1, max_depth=1, n_estimators=300; total time=   0.4s
[CV] END .............eta=0.1, max_depth=1, n_estimators=300; total time=   0.4s
[CV] END .............eta=0.1, max_depth=1, n_estimators=300; total time=   0.4s
[CV] END .............eta=0.1, max_depth=1, n_estimators=300; total time=   0.4s
[CV] END .............eta=0.1, max_depth=2, n_estimators=100; total time=   0.2s
[CV] END .............eta=0.1, max_depth=2, n_estimators=100; total time=   0.2s
[CV] END .............eta=0.1, max_depth=2, n_estimators=100; total time=   0.2s
[CV] END .............eta=0.1, max_depth=2, n_estimators=100; total time=   0.2s
[CV] END .............eta=0.1, max_depth=2, n_estimators=100; total time=   0.2s
[CV] END .............eta=0.1, max_depth=2, n_estimators=200; total time=   0.4s
[CV] END .............eta=0.1, max_depth=2, n_estimators=200; total time=   0.4s
[CV] END .............eta=0.1, max_depth=2, n_estimators=200; total time=   0.4s
[CV] END .............eta=0.1, max_depth=2, n_estimators=200; total time=   0.4s
[CV] END .............eta=0.1, max_depth=2, n_estimators=200; total time=   0.4s
[CV] END .............eta=0.1, max_depth=2, n_estimators=300; total time=   0.6s
[CV] END .............eta=0.1, max_depth=2, n_estimators=300; total time=   0.6s
[CV] END .............eta=0.1, max_depth=2, n_estimators=300; total time=   0.6s
[CV] END .............eta=0.1, max_depth=2, n_estimators=300; total time=   0.6s
[CV] END .............eta=0.1, max_depth=2, n_estimators=300; total time=   0.6s
[CV] END .............eta=0.1, max_depth=3, n_estimators=100; total time=   0.3s
[CV] END .............eta=0.1, max_depth=3, n_estimators=100; total time=   0.3s
[CV] END .............eta=0.1, max_depth=3, n_estimators=100; total time=   0.3s
[CV] END .............eta=0.1, max_depth=3, n_estimators=100; total time=   0.3s
[CV] END .............eta=0.1, max_depth=3, n_estimators=100; total time=   0.3s
[CV] END .............eta=0.1, max_depth=3, n_estimators=200; total time=   0.6s
[CV] END .............eta=0.1, max_depth=3, n_estimators=200; total time=   0.6s
[CV] END .............eta=0.1, max_depth=3, n_estimators=200; total time=   0.6s
[CV] END .............eta=0.1, max_depth=3, n_estimators=200; total time=   0.6s
[CV] END .............eta=0.1, max_depth=3, n_estimators=200; total time=   0.6s
[CV] END .............eta=0.1, max_depth=3, n_estimators=300; total time=   0.9s
[CV] END .............eta=0.1, max_depth=3, n_estimators=300; total time=   0.8s
[CV] END .............eta=0.1, max_depth=3, n_estimators=300; total time=   0.8s
[CV] END .............eta=0.1, max_depth=3, n_estimators=300; total time=   0.8s
[CV] END .............eta=0.1, max_depth=3, n_estimators=300; total time=   0.8s
[CV] END .............eta=0.1, max_depth=4, n_estimators=100; total time=   0.4s
[CV] END .............eta=0.1, max_depth=4, n_estimators=100; total time=   0.4s
[CV] END .............eta=0.1, max_depth=4, n_estimators=100; total time=   0.4s
[CV] END .............eta=0.1, max_depth=4, n_estimators=100; total time=   0.4s
[CV] END .............eta=0.1, max_depth=4, n_estimators=100; total time=   0.4s
[CV] END .............eta=0.1, max_depth=4, n_estimators=200; total time=   0.7s
[CV] END .............eta=0.1, max_depth=4, n_estimators=200; total time=   0.7s
[CV] END .............eta=0.1, max_depth=4, n_estimators=200; total time=   0.7s
[CV] END .............eta=0.1, max_depth=4, n_estimators=200; total time=   0.7s
[CV] END .............eta=0.1, max_depth=4, n_estimators=200; total time=   0.7s
[CV] END .............eta=0.1, max_depth=4, n_estimators=300; total time=   1.1s
[CV] END .............eta=0.1, max_depth=4, n_estimators=300; total time=   1.1s
[CV] END .............eta=0.1, max_depth=4, n_estimators=300; total time=   1.1s
[CV] END .............eta=0.1, max_depth=4, n_estimators=300; total time=   1.1s
[CV] END .............eta=0.1, max_depth=4, n_estimators=300; total time=   1.1s
[CV] END ............eta=0.01, max_depth=1, n_estimators=100; total time=   0.1s
[CV] END ............eta=0.01, max_depth=1, n_estimators=100; total time=   0.2s
[CV] END ............eta=0.01, max_depth=1, n_estimators=100; total time=   0.1s
[CV] END ............eta=0.01, max_depth=1, n_estimators=100; total time=   0.2s
[CV] END ............eta=0.01, max_depth=1, n_estimators=100; total time=   0.1s
[CV] END ............eta=0.01, max_depth=1, n_estimators=200; total time=   0.3s
[CV] END ............eta=0.01, max_depth=1, n_estimators=200; total time=   0.3s
[CV] END ............eta=0.01, max_depth=1, n_estimators=200; total time=   0.3s
[CV] END ............eta=0.01, max_depth=1, n_estimators=200; total time=   0.3s
[CV] END ............eta=0.01, max_depth=1, n_estimators=200; total time=   0.3s
[CV] END ............eta=0.01, max_depth=1, n_estimators=300; total time=   0.4s
[CV] END ............eta=0.01, max_depth=1, n_estimators=300; total time=   0.4s
[CV] END ............eta=0.01, max_depth=1, n_estimators=300; total time=   0.4s
[CV] END ............eta=0.01, max_depth=1, n_estimators=300; total time=   0.4s
[CV] END ............eta=0.01, max_depth=1, n_estimators=300; total time=   0.4s
[CV] END ............eta=0.01, max_depth=2, n_estimators=100; total time=   0.2s
[CV] END ............eta=0.01, max_depth=2, n_estimators=100; total time=   0.2s
[CV] END ............eta=0.01, max_depth=2, n_estimators=100; total time=   0.2s
[CV] END ............eta=0.01, max_depth=2, n_estimators=100; total time=   0.2s
[CV] END ............eta=0.01, max_depth=2, n_estimators=100; total time=   0.2s
[CV] END ............eta=0.01, max_depth=2, n_estimators=200; total time=   0.4s
[CV] END ............eta=0.01, max_depth=2, n_estimators=200; total time=   0.4s
[CV] END ............eta=0.01, max_depth=2, n_estimators=200; total time=   0.4s
[CV] END ............eta=0.01, max_depth=2, n_estimators=200; total time=   0.4s
[CV] END ............eta=0.01, max_depth=2, n_estimators=200; total time=   0.4s
[CV] END ............eta=0.01, max_depth=2, n_estimators=300; total time=   0.6s
[CV] END ............eta=0.01, max_depth=2, n_estimators=300; total time=   0.6s
[CV] END ............eta=0.01, max_depth=2, n_estimators=300; total time=   0.6s
[CV] END ............eta=0.01, max_depth=2, n_estimators=300; total time=   0.6s
[CV] END ............eta=0.01, max_depth=2, n_estimators=300; total time=   0.6s
[CV] END ............eta=0.01, max_depth=3, n_estimators=100; total time=   0.3s
[CV] END ............eta=0.01, max_depth=3, n_estimators=100; total time=   0.3s
[CV] END ............eta=0.01, max_depth=3, n_estimators=100; total time=   0.3s
[CV] END ............eta=0.01, max_depth=3, n_estimators=100; total time=   0.3s
[CV] END ............eta=0.01, max_depth=3, n_estimators=100; total time=   0.3s
[CV] END ............eta=0.01, max_depth=3, n_estimators=200; total time=   0.6s
[CV] END ............eta=0.01, max_depth=3, n_estimators=200; total time=   0.6s
[CV] END ............eta=0.01, max_depth=3, n_estimators=200; total time=   0.6s
[CV] END ............eta=0.01, max_depth=3, n_estimators=200; total time=   0.6s
[CV] END ............eta=0.01, max_depth=3, n_estimators=200; total time=   0.7s
[CV] END ............eta=0.01, max_depth=3, n_estimators=300; total time=   0.8s

[CV] END ............eta=0.01, max_depth=3, n_estimators=300; total time=   0.8s
[CV] END ............eta=0.01, max_depth=3, n_estimators=300; total time=   0.9s
[CV] END ............eta=0.01, max_depth=3, n_estimators=300; total time=   0.8s
[CV] END ............eta=0.01, max_depth=3, n_estimators=300; total time=   0.9s
[CV] END ............eta=0.01, max_depth=4, n_estimators=100; total time=   0.4s
[CV] END ............eta=0.01, max_depth=4, n_estimators=100; total time=   0.4s
[CV] END ............eta=0.01, max_depth=4, n_estimators=100; total time=   0.4s
[CV] END ............eta=0.01, max_depth=4, n_estimators=100; total time=   0.4s
[CV] END ............eta=0.01, max_depth=4, n_estimators=100; total time=   0.4s
[CV] END ............eta=0.01, max_depth=4, n_estimators=200; total time=   0.7s
[CV] END ............eta=0.01, max_depth=4, n_estimators=200; total time=   0.7s
[CV] END ............eta=0.01, max_depth=4, n_estimators=200; total time=   0.7s
[CV] END ............eta=0.01, max_depth=4, n_estimators=200; total time=   0.7s
[CV] END ............eta=0.01, max_depth=4, n_estimators=200; total time=   0.7s
[CV] END ............eta=0.01, max_depth=4, n_estimators=300; total time=   1.1s
[CV] END ............eta=0.01, max_depth=4, n_estimators=300; total time=   1.1s
[CV] END ............eta=0.01, max_depth=4, n_estimators=300; total time=   1.1s
[CV] END ............eta=0.01, max_depth=4, n_estimators=300; total time=   1.1s
[CV] END ............eta=0.01, max_depth=4, n_estimators=300; total time=   1.1s
[CV] END ...........eta=0.001, max_depth=1, n_estimators=100; total time=   0.1s
[CV] END ...........eta=0.001, max_depth=1, n_estimators=100; total time=   0.1s
[CV] END ...........eta=0.001, max_depth=1, n_estimators=100; total time=   0.1s
[CV] END ...........eta=0.001, max_depth=1, n_estimators=100; total time=   0.1s
[CV] END ...........eta=0.001, max_depth=1, n_estimators=100; total time=   0.1s
[CV] END ...........eta=0.001, max_depth=1, n_estimators=200; total time=   0.3s
[CV] END ...........eta=0.001, max_depth=1, n_estimators=200; total time=   0.3s
[CV] END ...........eta=0.001, max_depth=1, n_estimators=200; total time=   0.3s
[CV] END ...........eta=0.001, max_depth=1, n_estimators=200; total time=   0.3s
[CV] END ...........eta=0.001, max_depth=1, n_estimators=200; total time=   0.3s
[CV] END ...........eta=0.001, max_depth=1, n_estimators=300; total time=   0.4s
[CV] END ...........eta=0.001, max_depth=1, n_estimators=300; total time=   0.4s
[CV] END ...........eta=0.001, max_depth=1, n_estimators=300; total time=   0.4s
[CV] END ...........eta=0.001, max_depth=1, n_estimators=300; total time=   0.4s
[CV] END ...........eta=0.001, max_depth=1, n_estimators=300; total time=   0.4s
[CV] END ...........eta=0.001, max_depth=2, n_estimators=100; total time=   0.2s
[CV] END ...........eta=0.001, max_depth=2, n_estimators=100; total time=   0.2s
[CV] END ...........eta=0.001, max_depth=2, n_estimators=100; total time=   0.2s
[CV] END ...........eta=0.001, max_depth=2, n_estimators=100; total time=   0.2s
[CV] END ...........eta=0.001, max_depth=2, n_estimators=100; total time=   0.2s
[CV] END ...........eta=0.001, max_depth=2, n_estimators=200; total time=   0.4s
[CV] END ...........eta=0.001, max_depth=2, n_estimators=200; total time=   0.4s
[CV] END ...........eta=0.001, max_depth=2, n_estimators=200; total time=   0.4s
[CV] END ...........eta=0.001, max_depth=2, n_estimators=200; total time=   0.4s
[CV] END ...........eta=0.001, max_depth=2, n_estimators=200; total time=   0.4s
[CV] END ...........eta=0.001, max_depth=2, n_estimators=300; total time=   0.7s
[CV] END ...........eta=0.001, max_depth=2, n_estimators=300; total time=   0.7s
[CV] END ...........eta=0.001, max_depth=2, n_estimators=300; total time=   0.6s
[CV] END ...........eta=0.001, max_depth=2, n_estimators=300; total time=   0.7s
[CV] END ...........eta=0.001, max_depth=2, n_estimators=300; total time=   0.8s
[CV] END ...........eta=0.001, max_depth=3, n_estimators=100; total time=   0.3s
[CV] END ...........eta=0.001, max_depth=3, n_estimators=100; total time=   0.4s
[CV] END ...........eta=0.001, max_depth=3, n_estimators=100; total time=   0.4s
[CV] END ...........eta=0.001, max_depth=3, n_estimators=100; total time=   0.3s
[CV] END ...........eta=0.001, max_depth=3, n_estimators=100; total time=   0.3s
[CV] END ...........eta=0.001, max_depth=3, n_estimators=200; total time=   0.6s
[CV] END ...........eta=0.001, max_depth=3, n_estimators=200; total time=   0.6s
[CV] END ...........eta=0.001, max_depth=3, n_estimators=200; total time=   0.6s
[CV] END ...........eta=0.001, max_depth=3, n_estimators=200; total time=   0.5s
[CV] END ...........eta=0.001, max_depth=3, n_estimators=200; total time=   0.5s
[CV] END ...........eta=0.001, max_depth=3, n_estimators=300; total time=   0.8s
[CV] END ...........eta=0.001, max_depth=3, n_estimators=300; total time=   0.8s
[CV] END ...........eta=0.001, max_depth=3, n_estimators=300; total time=   0.8s
[CV] END ...........eta=0.001, max_depth=3, n_estimators=300; total time=   0.8s
[CV] END ...........eta=0.001, max_depth=3, n_estimators=300; total time=   0.8s
[CV] END ...........eta=0.001, max_depth=4, n_estimators=100; total time=   0.4s
[CV] END ...........eta=0.001, max_depth=4, n_estimators=100; total time=   0.4s
[CV] END ...........eta=0.001, max_depth=4, n_estimators=100; total time=   0.4s
[CV] END ...........eta=0.001, max_depth=4, n_estimators=100; total time=   0.4s
[CV] END ...........eta=0.001, max_depth=4, n_estimators=100; total time=   0.4s
[CV] END ...........eta=0.001, max_depth=4, n_estimators=200; total time=   0.7s
[CV] END ...........eta=0.001, max_depth=4, n_estimators=200; total time=   0.7s
[CV] END ...........eta=0.001, max_depth=4, n_estimators=200; total time=   0.7s
[CV] END ...........eta=0.001, max_depth=4, n_estimators=200; total time=   0.7s
[CV] END ...........eta=0.001, max_depth=4, n_estimators=200; total time=   0.7s
[CV] END ...........eta=0.001, max_depth=4, n_estimators=300; total time=   1.1s
[CV] END ...........eta=0.001, max_depth=4, n_estimators=300; total time=   1.1s
[CV] END ...........eta=0.001, max_depth=4, n_estimators=300; total time=   1.1s
[CV] END ...........eta=0.001, max_depth=4, n_estimators=300; total time=   1.1s
[CV] END ...........eta=0.001, max_depth=4, n_estimators=300; total time=   1.1s

GridSearchCV(estimator=XGBClassifier(base_score=None, booster=None,
                                     callbacks=None, colsample_bylevel=None,
                                     colsample_bynode=None,
                                     colsample_bytree=None,
                                     early_stopping_rounds=None,
                                     enable_categorical=False, eval_metric=None,
                                     feature_types=None, gamma=None,
                                     gpu_id=None, grow_policy=None,
                                     importance_type=None,
                                     interaction_constraints=None,
                                     learning_rate=None, max_bin=None,
                                     max_cat_threshold=None,
                                     max_cat_to_onehot=None,
                                     max_delta_step=None, max_depth=None,
                                     max_leaves=None, min_child_weight=None,
                                     missing=nan, monotone_constraints=None,
                                     n_estimators=100, n_jobs=None,
                                     num_parallel_tree=None, predictor=None,
                                     random_state=None, ...),
             param_grid={'eta': [0.1, 0.01, 0.001], 'max_depth': [1, 2, 3, 4],
                         'n_estimators': [100, 200, 300]},
             verbose=2)

In [90]:
cross_val.best_estimator_

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eta=0.01, eval_metric=None,
              feature_types=None, gamma=None, gpu_id=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=3,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, n_estimators=300, n_jobs=None,
              num_parallel_tree=None, predictor=None, ...)

In [91]:
## getting the best parameters

cross_val.best_params_

{'eta': 0.01, 'max_depth': 3, 'n_estimators': 300}

In [92]:


model1 = XGBClassifier(eta=0.1, max_depth=3, n_estimators=300)
model1.fit(X_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eta=0.1, eval_metric=None,
              feature_types=None, gamma=None, gpu_id=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=3,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, n_estimators=300, n_jobs=None,
              num_parallel_tree=None, predictor=None, ...)

In [93]:


y_pred1 = model1.predict(X_test)

In [94]:


accuracy_score(y_test,y_pred1)

0.8440366972477065